apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: chatbot-ingress
spec:
  entryPoints:
    - websecure
  tls:
    secretName: {{ .Release.Name }}-tls
  routes:
      - kind: Rule
        match: Host(`{{ .Values.host }}`)
        services:
          - name: chatbot
            port: 80